#!/bin/sh -e

if [ $# -ne 1 ] || [ "$1" = "--help" ]; then
  echo "Usage: $0 <image>"
  echo "Examples:"
  echo "  o lxc-start-me-up ubuntu-20-04"
  exit 1
fi

if [ "$(lxc list -c s -f csv $1)" != "RUNNING" ]; then
  lxc start "$1"
fi
until
  ip4_address=$(lxc list "$1" -c 4 -f csv | cut -f 1 -d ' ')
  [ -n "${ip4_address}" ]
do
  sleep 1
done
echo "${ip4_address}"
